# Generated by Django 5.0.6 on 2026-08-31 07:21

import apps.scanner.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='The uploaded leaf photo.', upload_to=apps.scanner.models.scan_image_upload_path)),
                ('disease_name', models.CharField(help_text='Human-readable disease name at the time of scanning.', max_length=255)),
                ('raw_label', models.CharField(help_text="Original model class label, e.g. 'Tomato___Late_blight'.", max_length=255)),
                ('confidence', models.FloatField(help_text="Model's confidence percentage (0-100) for this prediction.")),
                ('is_healthy', models.BooleanField(default=False)),
                ('symptoms', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='The user who submitted this scan.', on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scan History',
                'verbose_name_plural': 'Scan History',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='scanner_sca_user_id_8c123c_idx')],
            },
        ),
    ]
